name: Fix Env Vars

on:
  workflow_dispatch:

jobs:
  patch-env:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Update Kubeconfig
        run: aws eks update-kubeconfig --name project-bedrock-cluster --region us-east-1

      - name: Set Environment Variables
        run: |
          kubectl set env deployment/my-retail-app-ui -n retail-app \
            ENDPOINTS_CATALOG_URL=http://my-retail-app-catalog:80 \
            ENDPOINTS_CARTS_URL=http://my-retail-app-carts:80 \
            ENDPOINTS_CHECKOUT_URL=http://my-retail-app-checkout:80 \
            ENDPOINTS_ORDERS_URL=http://my-retail-app-orders:80 \
            ENDPOINTS_ASSETS_URL=http://my-retail-app-assets:80 \
            --overwrite

      - name: Verify Env Vars
        run: kubectl get deployment -n retail-app my-retail-app-ui -o yaml | grep -A 20 env:
